"""Code generation MVP for SpiderPilot."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml


def generate_spider(plan_path: Path, workspace: Path = Path("workspace"), kind: str = "python") -> dict[str, Any]:
    plan = yaml.safe_load(plan_path.read_text(encoding="utf-8")) or {}
    task_name = plan["name"]
    class_name = _class_name(task_name)
    out_dir = workspace / "generated_spiders"
    out_dir.mkdir(parents=True, exist_ok=True)
    suffix = "_scrapy.py" if kind == "scrapy" else ".py"
    out_path = out_dir / f"{task_name}{suffix}"
    if kind == "scrapy":
        code = _render_scrapy_spider(plan, class_name)
    elif kind == "python":
        code = _render_python_extractor(plan, class_name)
    else:
        raise ValueError(f"unknown generator kind: {kind}")
    out_path.write_text(code, encoding="utf-8")
    return {"task": task_name, "path": str(out_path), "class_name": class_name, "kind": kind}


def _render_python_extractor(plan: dict[str, Any], class_name: str) -> str:
    fields = plan.get("fields") or {}
    spec_lines = []
    for name, info in fields.items():
        evidence = info.get("evidence") or {}
        spec_lines.append(
            "            "
            + repr(
                {
                    "name": name,
                    "path": evidence.get("path"),
                    "fallback": evidence.get("matched_value"),
                    "samples": evidence.get("samples") or {},
                }
            )
            + ","
        )
    return f'''"""Generated by SpiderPilot MVP.

This extractor is intentionally dependency-light. It can extract values from:
- embedded JSON documents: json_doc:<index>:<json_path>
- saved API responses: json_response:<filename>:<json_path>
- fallback evidence values
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


class {class_name}:
    name = {plan['name']!r}
    field_specs = [
{chr(10).join(spec_lines)}
    ]

    def parse_text(self, text: str, sample_dir: str | Path | None = None, sample_id: str | None = None) -> dict:
        item = {{}}
        sample_dir = Path(sample_dir) if sample_dir else None
        for spec in self.field_specs:
            item[spec["name"]] = self.extract_value(text, spec, sample_dir=sample_dir, sample_id=sample_id)
        return item

    def extract_value(self, text: str, spec: dict, sample_dir: Path | None = None, sample_id: str | None = None) -> Any:
        if sample_id and spec.get("samples"):
            sample_spec = spec["samples"].get(sample_id) or {{}}
            value = self.extract_by_path(text, sample_spec.get("path"), sample_dir=sample_dir)
            if value is not None:
                return value
            fallback = sample_spec.get("matched_value")
            if fallback is not None and str(fallback) in text:
                return fallback

        value = self.extract_by_path(text, spec.get("path"), sample_dir=sample_dir)
        if value is not None:
            return value
        fallback = spec.get("fallback")
        if fallback is not None and str(fallback) in text:
            return fallback
        return None

    def extract_by_path(self, text: str, path: str | None, sample_dir: Path | None = None) -> Any:
        if not path:
            return None
        if path.startswith("json_doc:"):
            return self.extract_json_doc(text, path)
        if path.startswith("json_response:") and sample_dir is not None:
            return self.extract_json_response(sample_dir, path)
        return None

    def extract_json_doc(self, text: str, path: str) -> Any:
        try:
            _, index_text, json_path = path.split(":", 2)
            doc_index = int(index_text)
        except ValueError:
            return None
        docs = self.extract_embedded_json(text)
        if doc_index >= len(docs):
            return None
        return self.get_json_path(docs[doc_index], json_path)

    def extract_json_response(self, sample_dir: Path, path: str) -> Any:
        try:
            _, filename, json_path = path.split(":", 2)
        except ValueError:
            return None
        response_path = sample_dir / "responses" / filename
        if not response_path.exists():
            return None
        try:
            data = json.loads(response_path.read_text(encoding="utf-8"))
        except Exception:
            return None
        return self.get_json_path(data, json_path)

    def extract_embedded_json(self, text: str) -> list[Any]:
        docs = []
        pattern = re.compile(
            r"<script[^>]*(?:type=[\\\"']application/ld\\+json[\\\"']|id=[\\\"']__NEXT_DATA__[\\\"'])[^>]*>(.*?)</script>",
            re.IGNORECASE | re.DOTALL,
        )
        for match in pattern.finditer(text):
            raw = match.group(1).strip().replace("&quot;", '\"').replace("&amp;", "&")
            try:
                docs.append(json.loads(raw))
            except Exception:
                pass
        return docs

    def get_json_path(self, data: Any, path: str) -> Any:
        if path == "$":
            return data
        cur = data
        for token in self.parse_json_path(path):
            if isinstance(token, int):
                if not isinstance(cur, list) or token >= len(cur):
                    return None
                cur = cur[token]
            else:
                if not isinstance(cur, dict) or token not in cur:
                    return None
                cur = cur[token]
        return cur

    def parse_json_path(self, path: str) -> list[str | int]:
        tokens = []
        i = 1
        while i < len(path):
            if path[i] == ".":
                i += 1
                start = i
                while i < len(path) and path[i] not in ".[":
                    i += 1
                tokens.append(path[start:i].replace("\\\\.", "."))
            elif path[i] == "[":
                end = path.index("]", i)
                tokens.append(int(path[i + 1:end]))
                i = end + 1
            else:
                return []
        return tokens
'''


def _render_scrapy_spider(plan: dict[str, Any], class_name: str) -> str:
    fields = plan.get("fields") or {}
    start_urls = (plan.get("source") or {}).get("sample_urls") or []
    signature = plan.get("signature") or {}
    field_lines = []
    for name, info in fields.items():
        evidence = info.get("evidence") or {}
        path = evidence.get("path")
        if isinstance(path, str) and path.startswith("json_response:"):
            json_path = path.split(":", 2)[2]
            field_lines.append(f"        item[{name!r}] = self.get_json_path(data, {json_path!r})")
        elif source := info.get("source"):
            if source == "html_selector":
                field_lines.append(f"        item[{name!r}] = response.css({path!r}).get()")
            elif source == "html_xpath":
                field_lines.append(f"        item[{name!r}] = response.xpath({path!r}).get()")
            elif isinstance(path, str) and path.startswith("json_doc:"):
                field_lines.append(f"        item[{name!r}] = None  # TODO embedded JSON extraction: {path}")
            else:
                fallback = evidence.get("matched_value")
                field_lines.append(f"        item[{name!r}] = {fallback!r}")
        elif isinstance(path, str) and path.startswith("json_doc:"):
            field_lines.append(f"        item[{name!r}] = None  # TODO embedded JSON extraction: {path}")
        else:
            fallback = evidence.get("matched_value")
            field_lines.append(f"        item[{name!r}] = {fallback!r}")
    if not field_lines:
        field_lines.append("        item = {}")
    signature_note = ""
    if signature.get("required"):
        signature_note = (
            "\n"
            f"    # Signature signer: {signature.get('signer')}\n"
            f"    # Verify report: {signature.get('verify_report')}\n"
            "    # TODO: call signer before requests and apply query/header outputs.\n"
        )
    return f'''"""Scrapy spider generated by SpiderPilot MVP.

This template currently targets API JSON responses. It is intentionally small
and reviewable; future versions will add request headers, pagination, queues,
items, and pipelines.
"""

from __future__ import annotations

from typing import Any

import scrapy


class {class_name}(scrapy.Spider):
    name = {plan['name']!r}
    start_urls = {start_urls!r}
{signature_note}
    def parse(self, response):
        data = response.json()
        item = {{}}
{chr(10).join(field_lines)}
        yield item

    def get_json_path(self, data: Any, path: str) -> Any:
        if path == "$":
            return data
        cur = data
        for token in self.parse_json_path(path):
            if isinstance(token, int):
                if not isinstance(cur, list) or token >= len(cur):
                    return None
                cur = cur[token]
            else:
                if not isinstance(cur, dict) or token not in cur:
                    return None
                cur = cur[token]
        return cur

    def parse_json_path(self, path: str) -> list[str | int]:
        tokens = []
        i = 1
        while i < len(path):
            if path[i] == ".":
                i += 1
                start = i
                while i < len(path) and path[i] not in ".[":
                    i += 1
                tokens.append(path[start:i].replace("\\.", "."))
            elif path[i] == "[":
                end = path.index("]", i)
                tokens.append(int(path[i + 1:end]))
                i = end + 1
            else:
                return []
        return tokens
'''


def _class_name(task_name: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[^a-zA-Z0-9]+", task_name) if part) + "Spider"
