"""Code generation MVP for SpiderPilot."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml


def generate_spider(plan_path: Path, workspace: Path = Path("workspace")) -> dict[str, Any]:
    plan = yaml.safe_load(plan_path.read_text(encoding="utf-8")) or {}
    task_name = plan["name"]
    class_name = _class_name(task_name)
    out_dir = workspace / "generated_spiders"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{task_name}.py"
    code = _render_python_extractor(plan, class_name)
    out_path.write_text(code, encoding="utf-8")
    return {"task": task_name, "path": str(out_path), "class_name": class_name}


def _render_python_extractor(plan: dict[str, Any], class_name: str) -> str:
    fields = plan.get("fields") or {}
    field_lines = []
    for name, info in fields.items():
        evidence = info.get("evidence") or {}
        path = evidence.get("path")
        value = evidence.get("matched_value")
        # MVP generated code records extraction evidence. JSON paths are surfaced
        # in comments for review; later versions will emit full Scrapy extraction.
        if isinstance(path, str) and path.startswith("json_doc:"):
            field_lines.append(f"        # {name}: {path}")
        field_lines.append(f"        item[{name!r}] = {value!r}")
    if not field_lines:
        field_lines.append("        item = {}")
    return f'''"""Generated by SpiderPilot MVP.

This is a lightweight extractor generated from an Extraction Plan. Current MVP
plans use raw_html text-offset evidence; future codegen will emit Scrapy
Requests plus CSS/XPath/JSONPath/API extraction logic.
"""


class {class_name}:
    name = {plan['name']!r}

    def parse_text(self, text: str) -> dict:
        item = {{}}
{chr(10).join(field_lines)}
        return item
'''


def _class_name(task_name: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[^a-zA-Z0-9]+", task_name) if part) + "Spider"
