"""Signer skeleton generator MVP."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

from spiderpilot.spec import load_spec


def generate_signer_skeleton(spec_path: Path, workspace: Path = Path("workspace")) -> dict[str, Any]:
    spec = load_spec(spec_path)
    sig_dir = workspace / "signatures" / spec.name
    samples_path = sig_dir / "samples.json"
    samples = json.loads(samples_path.read_text(encoding="utf-8")) if samples_path.exists() else []
    groups = _group_samples(samples)
    signer_js = _render_signer_stub(groups)
    signer_path = sig_dir / "signer_stub.js"
    signer_path.write_text(signer_js, encoding="utf-8")
    manifest = {
        "version": 1,
        "task": spec.name,
        "kind": "signer_stub",
        "signer_path": str(signer_path),
        "groups": groups,
        "next_steps": [
            "inspect samples and request construction",
            "locate JS generation function using runtime stack/source search",
            "replace TODO in signer_stub.js",
            "run signature-verify",
        ],
    }
    (sig_dir / "signature.yaml").write_text(yaml.safe_dump(manifest, allow_unicode=True, sort_keys=False), encoding="utf-8")
    return manifest


def _group_samples(samples: list[dict[str, Any]]) -> list[dict[str, Any]]:
    groups: dict[tuple[str, str], dict[str, Any]] = {}
    for sample in samples:
        key = (sample.get("location", "unknown"), sample.get("key", "unknown"))
        group = groups.setdefault(
            key,
            {
                "location": key[0],
                "key": key[1],
                "classification": sample.get("classification"),
                "samples": [],
            },
        )
        if len(group["samples"]) < 10:
            group["samples"].append(sample)
    return list(groups.values())


def _render_signer_stub(groups: list[dict[str, Any]]) -> str:
    return """// Generated by SpiderPilot Signature Generator MVP.\n""" + f"""
const signatureGroups = {json.dumps(groups, ensure_ascii=False, indent=2)};

/**
 * TODO: Replace this stub with the recovered signing algorithm.
 *
 * Expected input shape:
 *   {{ url, method, query, headers, body, cookies, timestamp }}
 *
 * Expected output shape:
 *   {{ query: {{...}}, headers: {{...}}, body: ... }}
 */
function sign(input) {{
  const output = {{ query: {{}}, headers: {{}}, body: input.body ?? null }};
  for (const group of signatureGroups) {{
    const sample = group.samples && group.samples[0];
    if (!sample) continue;
    // Placeholder behavior: replay first sample value for integration testing.
    // This is NOT a real signer. Use signature-verify to confirm failure/success.
    if (group.location === 'query') output.query[group.key] = sample.value;
    else if (group.location === 'request_header' || group.location === 'header') output.headers[group.key] = sample.value;
  }}
  return output;
}}

if (require.main === module) {{
  let raw = '';
  process.stdin.on('data', chunk => raw += chunk);
  process.stdin.on('end', () => {{
    const input = raw ? JSON.parse(raw) : {{}};
    process.stdout.write(JSON.stringify(sign(input), null, 2));
  }});
}}

module.exports = {{ sign, signatureGroups }};
"""
